# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=750)),
                ('token', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('group_text_with_location', models.BooleanField(default=True)),
                ('group_photo_with_location', models.BooleanField(default=True)),
                ('location_first', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(db_index=True, max_length=50)),
                ('chat_id', models.CharField(db_index=True, max_length=50)),
                ('telegram_message_id', models.IntegerField()),
                ('when_sent', models.DateTimeField()),
                ('when_registered', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Bot')),
                ('text', models.CharField(default='', max_length=2000)),
                ('photo_thumb', models.FileField(upload_to='images/')),
                ('photo_hires', models.FileField(upload_to='images/')),
                ('photo_caption', models.CharField(default='', max_length=2000)),
                ('longitude', models.FloatField(blank=True, null=True, db_index=True)),
                ('latitude', models.FloatField(blank=True, null=True, db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Segnalazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('username', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='segnalazione',
            name='location_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segnalazione_location', to='bot.TelegramMessage'),
        ),
        migrations.AddField(
            model_name='segnalazione',
            name='photo_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segnalazione_photo', to='bot.TelegramMessage'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.TelegramUser'),
        ),
    ]
